version: "3.9"

services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    depends_on:
      - bot

  bot:
    build:
      context: ./apps/bot
    env_file:
      - ./.env

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL:-}
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
