services:
  web:
    build:
      context: ./apps/web
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

  bot:
    build:
      context: ./apps/bot
    env_file:
      - ./.env
    volumes:
      - ./apps/bot:/app
    depends_on:
      - web
